---
# tasks file for myapache
 - name: installing httpd and php
   package:
          name:
                  - httpd
                  - php
          state: present

 - name: Start and enable httpd
   service:
           name: httpd
           state: started
           enabled: true

 - name: Disable firewalld
   firewalld:
          port: 80/tcp
          state: enabled
          permanent: yes
          immediate: yes

 - name: Making SElinux permissive
   selinux:
           policy: targeted
           state: permissive

 - name: Copying Files to document root folder
   copy:
           src: files/php/index.php
           dest: "/var/www/html/"
   notify:
           - restart httpd

